fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-merge-conflict
-   repo: https://github.com/pycqa/pylint
    rev: v2.17.1
    hooks:
    - id: pylint
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
    - id: clang-format
      types_or: [c++, c, cuda]
